version: '3'

services:
  api:
    build: mock-emailapi/
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  gmail:
    build: mock-gmail/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Zedila01
      POSTGRES_DB: email_server
