version: '3'

services:
  api:
    build: mock-emailapi/
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  gmail:
    build: mock-gmail/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=emails
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql